map_of_headers = {
    "Industry": {"overview": 1},
    "Market Cap": {"overview": 2},
    "Closing Price": {"overview": 3},
    "1 Year % Change": {"overview": 4},
    "P/E Ratio": {"overview": 5},
    "Dividend Yield": {"overview": 6},

    "Exchange": {"descriptive": 2},
    "Country": {"descriptive": 3},
    "Sector": {"descriptive": 4},

    "12 Month Dividend": {"dividend": 3},
    "12 Month EPS": {"dividend": 4},
    "Dividend Payout Ratio": {"dividend": 5},

    "1 Week % Change": {"performance_st": 1},
    "1 Month % Change": {"performance_st": 2},
    "3 Month % Change": {"performance_st": 3},
    "6 Month % Change": {"performance_st": 4},
    "YTD % Change": {"performance_st": 5},
    "Price vs 50D SMA": {"performance_st": 7},
    "Pricec vs 200D SMA": {"performance_st": 8},

    "3 Year CAGR %": {"performance_lt": 1},
    "5 Year CAGR %": {"performance_lt": 2},
    "10 Year CAGR %": {"performance_lt": 3},
    "20 Year CAGR %": {"performance_lt": 4},
    "30 Year CAGR %": {"performance_lt": 5},
    "40 Year CAGR %": {"performance_lt": 6},
    "50 Year CAGR %": {"performance_lt": 7},

    "Price/Earnings Ratio": {"ratios_income": 1},
    "PEG Ratio": {"ratios_income": 2},
    "Price/Sales Ratio": {"ratios_income": 3},
    "Operating Margin": {"ratios_income": 4},
    "Pre-Tax Margin": {"ratios_income": 5},
    "Net Margin": {"ratios_income": 6},

    "Price/Book Ratio": {"ratios_debt": 1},
    r"Price/Cash\ Ratio": {"ratios_debt": 2},
    "Return on Equity": {"ratios_debt": 3},
    "Return on Assets": {"ratios_debt": 4},
    "Inventory Turnover": {"ratios_debt": 5},
    "Current Ratio": {"ratios_debt": 6},
    "Quick Ratio": {"ratios_debt": 7},
    "Debt/Equity Ratio": {"ratios_debt": 8},

    "12 Month Sales Growth": {"rev_earnings": 1},
    "5 Year\nSales Growth": {"rev_earnings": 2},
    "12 Month\nEPS Growth": {"rev_earnings": 3},
    "5 Year\nEPS Growth": {"rev_earnings": 4},
    "Last Quarter\nEPS Surprise %": {"rev_earnings": 5},
    "Estimated EPS\nGrowth Next Year": {"rev_earnings": 6},
}
